# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here    
      mkdir rep 
      cat << EOF > 'rep/sample.html'
      <html><h2>My Cstom Report</h2>
      <body bgcolor=silver> Testing HTML reports on azure</body>
      </html> 
      EOF
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PublishHtmlReport@1
  inputs:
    reportDir: 'rep/sample.html'